services:
  mtslinker:
    build: .
    container_name: mtslinker
    volumes:
      - .:/app
    # Пример запуска с URL (можно переопределить при вызове)
    command: ["https://my.mts-link.ru/Cloud/856071692/record-new/1482280531",  "--session-id", "6049ae8bedcf8d8e1960da528e5cc18b"] 
